# fly.toml app configuration file
app = "atomichack-log-monitor-api"
primary_region = "ams"  # Amsterdam (ближайший к России)

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  PORT = "8001"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

