services:
  - type: web
    name: atomichack-log-monitor-api
    runtime: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
